require:
  - rubocop-rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

RSpec/MultipleExpectations:
  Max: 5

AllCops:
  TargetRubyVersion: 2.7
