require:
  - rubocop-rails

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 100

RSpec/AnyInstance:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.7
